"""baseline: 4 tables from v1.2

Revision ID: 6438afda32c3
Revises: 
Create Date: 2026-03-28 16:16:20.902698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6438afda32c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('origins', sa.JSON(), nullable=False),
    sa.Column('destinations', sa.JSON(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('travel_start', sa.Date(), nullable=False),
    sa.Column('travel_end', sa.Date(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('max_stops', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('silenced_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_group_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('airline', sa.String(length=2), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_first_quartile', sa.Float(), nullable=True),
    sa.Column('price_median', sa.Float(), nullable=True),
    sa.Column('price_third_quartile', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('price_classification', sa.String(length=10), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['route_group_id'], ['route_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_class_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.String(length=1), nullable=False),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.Column('segment_direction', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['flight_snapshot_id'], ['flight_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detected_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_group_id', sa.Integer(), nullable=False),
    sa.Column('flight_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=False),
    sa.Column('price_at_detection', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['flight_snapshot_id'], ['flight_snapshots.id'], ),
    sa.ForeignKeyConstraint(['route_group_id'], ['route_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_dedup', 'detected_signals', ['route_group_id', 'origin', 'destination', 'departure_date', 'return_date', 'signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_dedup', table_name='detected_signals')
    op.drop_table('detected_signals')
    op.drop_table('booking_class_snapshots')
    op.drop_table('flight_snapshots')
    op.drop_table('route_groups')
    # ### end Alembic commands ###
